import {afterAll,beforeAll,describe,expect,it} from 'vitest';import {Miniflare,convertV4MiniflareOptions} from 'miniflare';import {mkdtempSync,readFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {administerIntelligenceSupplyGrant,type IntelligenceSupplyGrantCommand} from '../src/authority/intelligence-supply-grant';import {loadCurrentEmission,persistEmission} from '../src/authority/emission-store';import {withBuiltinCatalog} from '../src/authority/emission';import {registerInstallationKey} from '../src/authority/identity';import type {WireFullContent} from '../src/authority/schema';
let db:D1Database,mf:Miniflare,temp:string,privateKey:ArrayBuffer;const org='supply-org',installation='installation-1',now='2026-09-30T12:00:00Z';const actor={organizationId:org,principalId:'master-human',sessionId:'session',expiresAt:'2026-09-30T13:00:00Z',source:'backend-session' as const};
const services=()=>({now:()=>now,signer:{privateKeyPkcs8:privateKey,keyId:'issuer-key'},commitGuard:()=>db.prepare('SELECT 1')});
const load=async(file:string)=>{const sql=readFileSync(join(process.cwd(),'migrations',file),'utf8').replace(/--[^\r\n]*/g,'').trim();for(const s of sql.split(/;\s*(?=(?:CREATE|ALTER)\b)/i).filter(Boolean))await db.prepare(s).run();};
beforeAll(async()=>{temp=mkdtempSync(join(tmpdir(),'authority-supply-grant-'));mf=new Miniflare({...convertV4MiniflareOptions({host:'127.0.0.1',cf:false,modules:true,script:'export default {fetch(){return new Response("fixture")}}',compatibilityDate:'2026-08-29',d1Databases:{DB:'supply'}}),resourcePersistencePath:temp});db=await mf.getD1Database('DB') as unknown as D1Database;await db.prepare('CREATE TABLE organizations(id TEXT PRIMARY KEY)').run();for(const f of ['0001_authority_snapshot.sql','0002_authority_security.sql','0004_authority_emissions.sql','0005_authority_administration.sql','0022_authority_intelligence_supply_grants.sql'])await load(f);await db.prepare('INSERT INTO organizations VALUES(?)').bind(org).run();
 const pair=await crypto.subtle.generateKey({name:'Ed25519'},true,['sign','verify']) as CryptoKeyPair;privateKey=await crypto.subtle.exportKey('pkcs8',pair.privateKey) as ArrayBuffer;const pub=Buffer.from(await crypto.subtle.exportKey('raw',pair.publicKey)).toString('base64');await registerInstallationKey(db,{installationId:installation,organizationId:org,publicKeyRaw:pub,supportedAuthoritySchemaVersions:['1.0','1.1']});
 const state:WireFullContent=withBuiltinCatalog({principals:[{principal_id:actor.principalId,principal_type:'human',status:'active',external_identities:[{provider:'github',subject:'master',display_handle:'master',status:'verified',verified_at:now}]}],memberships:[{membership_id:'membership',principal_id:actor.principalId,organization_id:org,status:'active',valid_from:now,valid_until:null,accepted_at:now}],role_definitions:[],role_assignments:[{assignment_id:'master-assignment',membership_id:'membership',role_id:'master',role_version:'1',scope:{type:'organization',id:org},status:'active',valid_from:now,valid_until:null,accepted_at:now}],revocations:[]});
 await persistEmission(db,{requestId:'initial',expectedVersion:null,metadata:{schema:'bloom.authority.snapshot',schema_version:'1.0',snapshot_id:'initial',issuer:'issuer',organization_id:org,authority_version:'1',issued_at:now,not_before:now,expires_at:'2026-09-30T12:04:00Z',audience:{organization_id:org,installation_ids:[installation]}},state,initialFixtureEvidence:{environment:'test',reference:'supply'}},{...services().signer,allowTestFixtures:true});
},60000);afterAll(async()=>{await mf?.dispose();if(temp)rmSync(temp,{recursive:true,force:true});});
const issue:Extract<IntelligenceSupplyGrantCommand,{kind:'issue'}>={kind:'issue',installationIds:[installation],consumerId:'brain',actorPrincipalId:actor.principalId,purpose:'mandate_intelligence',allowedCapabilities:['text.generate','structured_output','tool_call.propose'],allowedPrivacy:['approved_cloud'],allowedDestinations:[{provider:'anthropic',backendId:'anthropic_api',models:['claude-model']}],limits:{maxTotalTokens:10000,maxOutputTokensPerInference:2000,maxInferences:5,maxUsd:'1.500000'},validUntil:'2026-10-01T12:00:00Z',replacesGrantId:null};
describe('Intelligence Supply Grant administration',()=>{
 it('issues under wire 1.1, replays and rejects conflicts',async()=>{const input={organizationId:org,requestId:'issue-1',expectedVersion:'1',command:issue};const result=await administerIntelligenceSupplyGrant(db,input,actor,services());expect(result).toMatchObject({status:'issued',authorityVersion:'2',validFrom:now});expect(await administerIntelligenceSupplyGrant(db,input,actor,services())).toEqual(result);await expect(administerIntelligenceSupplyGrant(db,{...input,command:{...issue,allowedCapabilities:['text.generate']}},actor,services())).rejects.toThrow('idempotency_conflict');const current=(await loadCurrentEmission(db,org))!;expect(current.metadata.schema_version).toBe('1.1');expect(current.state.intelligence_supply_grants).toHaveLength(1);expect(current.state.intelligence_supply_grants![0]).toMatchObject({purpose:'mandate_intelligence',allowed_capabilities:['structured_output','text.generate','tool_call.propose'],issued_by_principal_id:actor.principalId});});
 it('atomically replaces and then revokes without mutating history',async()=>{const first=(await loadCurrentEmission(db,org))!.state.intelligence_supply_grants![0];const replacement=await administerIntelligenceSupplyGrant(db,{organizationId:org,requestId:'replace',expectedVersion:'2',command:{...issue,replacesGrantId:first.grant_id}},actor,services());expect(replacement.status).toBe('issued');let state=(await loadCurrentEmission(db,org))!.state;expect(state.intelligence_supply_grants).toHaveLength(2);expect(state.revocations.some(r=>r.target_type==='intelligence_supply_grant'&&r.target_id===first.grant_id&&r.reason_code==='grant_replaced')).toBe(true);const revoked=await administerIntelligenceSupplyGrant(db,{organizationId:org,requestId:'revoke',expectedVersion:'3',command:{kind:'revoke',grantId:replacement.grantId}},actor,services());expect(revoked.status).toBe('revoked');state=(await loadCurrentEmission(db,org))!.state;expect(state.intelligence_supply_grants).toHaveLength(2);expect(state.revocations.some(r=>r.target_type==='intelligence_supply_grant'&&r.target_id===replacement.grantId&&r.reason_code==='master_revocation')).toBe(true);});
 it('keeps administrative history immutable',async()=>{await expect(db.prepare('UPDATE authority_intelligence_supply_grant_requests SET operation=operation').run()).rejects.toThrow('history_immutable');});
});
