import {beforeAll,afterAll,describe,it,expect} from 'vitest';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';import {readFileSync,mkdtempSync,rmSync,writeFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';import {spawnSync} from 'node:child_process';
import {signTrustManifest,verifyTrustManifest,persistTrustManifest,loadTrustManifest,type TrustPayload} from '../src/authority/trust-manifest';
import {authorityTrustResponse,type TrustRouteServices} from '../src/authority/trust-route';
import {beginHumanLogin,finishHumanLogin,type HumanServices} from '../src/authority/human-session-store';
import {base64ToBase64url,canonicalizeJson,signWithDomain} from '../src/authority/canonical';
let db:D1Database,mf:Miniflare,temp:string,rootPrivate:ArrayBuffer,rootPublic:string,issuerPrivate:ArrayBuffer,issuerPublic:string,n=0,actorAttestation='',actorChallenge='',actorPublic='',actorOrg='';
const now='2026-09-09T12:00:00Z',origin='https://authority.test',rootID='root-test';
async function keys():Promise<{privateKey:ArrayBuffer;publicKey:string}>{const pair=await crypto.subtle.generateKey('Ed25519',true,['sign','verify']) as CryptoKeyPair;return {privateKey:await crypto.subtle.exportKey('pkcs8',pair.privateKey) as ArrayBuffer,publicKey:base64ToBase64url(Buffer.from(await crypto.subtle.exportKey('raw',pair.publicKey) as ArrayBuffer).toString('base64'))};}
const provider={source:'test-fixture' as const,authorize:()=> 'https://fixture.test',exchange:async()=>({token:'owner-provider',expiresIn:28800}),identify:async()=>({subject:'123',handle:'owner'})};
function payload(org:string,version='1',keysOverride?:TrustPayload['keys']):TrustPayload{return {schema:'bloom.authority.trust-manifest',schema_version:'1.0',manifest_id:`manifest-${org}-${version}`,issuer:'issuer-test',organization_id:org,manifest_version:version,issued_at:now,not_before:now,expires_at:'2026-09-10T12:00:00Z',root_key_id:rootID,keys:keysOverride??[{key_id:'issuer-key',public_key:issuerPublic,status:'active',valid_from:now,valid_until:null}]};}
beforeAll(async()=>{const root=await keys(),issuer=await keys();rootPrivate=root.privateKey;rootPublic=root.publicKey;issuerPrivate=issuer.privateKey;issuerPublic=issuer.publicKey;
 temp=mkdtempSync(join(tmpdir(),'authority-3-trust-'));mf=new Miniflare({...convertV4MiniflareOptions({host:'127.0.0.1',cf:false,modules:true,script:'export default {fetch(){return new Response("fixture")}}',compatibilityDate:'2026-08-29',d1Databases:{DB:'trust'}}),resourcePersistencePath:temp});db=await mf.getD1Database('DB') as unknown as D1Database;
 await db.prepare('CREATE TABLE organizations(id TEXT PRIMARY KEY)').run();await db.prepare('CREATE TABLE authority_admin_requests(organization_id TEXT,request_id TEXT,actor_id TEXT,PRIMARY KEY(organization_id,request_id))').run();
 for(const file of ['0006_authority_human_identity.sql','0007_authority_trust.sql']){const sql=readFileSync(new URL('../migrations/'+file,import.meta.url),'utf8').replace(/--[^\r\n]*/g,'').trim();for(const part of sql.split(/;\s*(?=CREATE\b)/i))await db.prepare(part).run();}
},60000);afterAll(async()=>{await mf?.dispose();if(temp)rmSync(temp,{recursive:true,force:true});});
async function org(){const id=`trust-${++n}`;await db.prepare('INSERT INTO organizations VALUES(?)').bind(id).run();return id;}
describe('rooted Authority trust on temporary D1',()=>{
 it('signs, normalizes and verifies only against the externally supplied root',async()=>{const p=payload(await org()),e=await signTrustManifest(p,rootPrivate);expect((await verifyTrustManifest(e,rootID,rootPublic,'2026-09-09T12:01:00Z')).keys[0].key_id).toBe('issuer-key');const other=await keys();await expect(verifyTrustManifest(e,rootID,other.publicKey,'2026-09-09T12:01:00Z')).rejects.toThrow('signature_invalid');await expect(verifyTrustManifest(e,'issuer-key',issuerPublic,'2026-09-09T12:01:00Z')).rejects.toThrow();});
 it('persists immutable monotonic manifests and rejects fixture provisioning unless explicit',async()=>{const id=await org(),one=await signTrustManifest(payload(id),rootPrivate);await expect(persistTrustManifest(db,one)).rejects.toThrow('provisioning_unavailable');const raw=await persistTrustManifest(db,one,{allowTestFixtures:true,expectedVersion:null});expect(await loadTrustManifest(db,id)).toBe(raw);const nextKey=await keys(),two=await signTrustManifest(payload(id,'2',[{...payload(id).keys[0],status:'retired',valid_until:'2026-09-09T12:02:00Z'},{key_id:'issuer-key-2',public_key:nextKey.publicKey,status:'active',valid_from:now,valid_until:null}]),rootPrivate);await persistTrustManifest(db,two,{allowTestFixtures:true,expectedVersion:'1'});expect(JSON.parse((await loadTrustManifest(db,id))!).payload.manifest_version).toBe('2');const three=await signTrustManifest(payload(id,'3'),rootPrivate);await expect(persistTrustManifest(db,three,{allowTestFixtures:true,expectedVersion:'1'})).rejects.toThrow('version_conflict');await expect(db.prepare("UPDATE authority_trust_manifests SET issuer='other' WHERE organization_id=?").bind(id).run()).rejects.toThrow('immutable');await expect(db.prepare('DELETE FROM authority_trust_heads WHERE organization_id=?').bind(id).run()).rejects.toThrow('immutable');});
 it('rejects expired manifests, duplicate keys and invalid key windows',async()=>{const id=await org(),e=await signTrustManifest(payload(id),rootPrivate);await expect(verifyTrustManifest(e,rootID,rootPublic,'2026-09-10T12:00:00Z')).rejects.toThrow('manifest_expired');await expect(signTrustManifest(payload(id,'1',[payload(id).keys[0],payload(id).keys[0]]),rootPrivate)).rejects.toThrow('key_invalid');await expect(signTrustManifest(payload(id,'1',[{...payload(id).keys[0],valid_until:now}]),rootPrivate)).rejects.toThrow('key_invalid');});
 it('requires installation challenge, local possession and authenticated human approval',async()=>{
  const id=await org();await persistTrustManifest(db,await signTrustManifest(payload(id),rootPrivate),{allowTestFixtures:true});await db.prepare("INSERT INTO authority_human_identities VALUES(?,?,'123','fixture:explicit','test-fixture','1','active',NULL,'')").bind(id,'owner').run();
  const hs:HumanServices={provider,encryptionKey:Buffer.alloc(32,8).toString('base64'),now:()=>now,allowTestFixtures:true},flow=await beginHumanLogin(db,id,hs),login=await finishHumanLogin(db,{...flow,code:'fixture'},hs);
  const s:TrustRouteServices={...hs,origin,issuer:'issuer-test',attestationKeyId:'issuer-key',attestationPrivateKeyPkcs8:issuerPrivate};const actor=await keys();
  const challengeResponse=await authorityTrustResponse(db,new Request(origin+`/v1/authority/actor/challenge?org=${id}`,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({organizationId:id,actorPublicKey:actor.publicKey,audience:'bloom.authority.local-actor'})}),s,{organizationId:id,installationId:'installation-a'});expect(challengeResponse.status).toBe(201);const challenge=await challengeResponse.json() as any;
  const possession={challenge:challenge.challenge,organization_id:id,installation_id:'installation-a',audience:'bloom.authority.local-actor'},signature=base64ToBase64url(await signWithDomain('BLOOM-AUTHORITY-ACTOR-PROOF-v1',canonicalizeJson(possession),actor.privateKey));
  const approvalBody={organizationId:id,installationId:'installation-a',actorPublicKey:actor.publicKey,audience:'bloom.authority.local-actor',challenge:challenge.challenge,signature};
  const approve=()=>authorityTrustResponse(db,new Request(origin+'/v1/authority/actor/approve',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json',Cookie:`__Host-authority-session=${login.token}`,'X-Authority-CSRF':login.csrf},body:JSON.stringify(approvalBody)}),s,null);
  const accepted=await approve();expect(accepted.status).toBe(200);actorAttestation=await accepted.clone().text();actorChallenge=challenge.challenge;actorPublic=actor.publicKey;actorOrg=id;expect((await accepted.json() as any).payload).toMatchObject({principal_id:'owner',organization_id:id,installation_id:'installation-a',actor_public_key:actor.publicKey});expect((await approve()).status).toBe(403);
  const wrong=await keys(),bad=await authorityTrustResponse(db,new Request(origin+`/v1/authority/actor/challenge?org=${id}`,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({organizationId:id,actorPublicKey:wrong.publicKey,audience:'other'})}),s,{organizationId:id,installationId:'installation-a'});expect(bad.status).toBe(403);
 });
 it('serves exact persisted manifest only to the bound installation',async()=>{const id=await org(),e=await signTrustManifest(payload(id),rootPrivate),raw=await persistTrustManifest(db,e,{allowTestFixtures:true});const s:TrustRouteServices={provider,encryptionKey:Buffer.alloc(32).toString('base64'),now:()=>now,allowTestFixtures:true,origin,issuer:'issuer-test',attestationKeyId:'issuer-key',attestationPrivateKeyPkcs8:issuerPrivate};const ok=await authorityTrustResponse(db,new Request(origin+`/v1/authority/trust-manifest?org=${id}`),s,{organizationId:id,installationId:'installation-a'});expect(await ok.text()).toBe(raw);expect((await authorityTrustResponse(db,new Request(origin+`/v1/authority/trust-manifest?org=${id}`),s,{organizationId:'other',installationId:'installation-a'})).status).toBe(401);});
 it('exchanges freshly signed trust and actor artifacts with Go',async()=>{const e=await signTrustManifest(payload(actorOrg),rootPrivate),artifact=join(temp,'trust-interop.json');writeFileSync(artifact,JSON.stringify({manifest:e,root_key_id:rootID,root_public_key:rootPublic,now:'2026-09-09T12:01:00Z',organization_id:actorOrg,issuer:'issuer-test',actor_attestation:JSON.parse(actorAttestation),actor_challenge:actorChallenge,actor_public_key:actorPublic,installation_id:'installation-a'}));const goRoot=resolve(new URL('../../installer/nucleus',import.meta.url).pathname.replace(/^\/([A-Za-z]:)/,'$1'));const run=spawnSync('go',['test','./internal/authority','-run','^TestTrustManifestBackendInterop$','-count=1','-v'],{cwd:goRoot,encoding:'utf8',env:{...process.env,AUTHORITY_TRUST_ARTIFACT:artifact,GOPROXY:'off',GOCACHE:join(temp,'go-cache')}});expect(run.status,run.stdout+run.stderr).toBe(0);},60000);
});
