import {afterAll,beforeAll,beforeEach,describe,expect,it} from 'vitest';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {mkdtempSync,readFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {claimProject,getProjectBinding,ProjectClaimError} from '../src/authority/project-claim';
import app from '../src/index';
import {canonicalizeJson,signWithDomain} from '../src/authority/canonical';
import {generateKeyPairSync} from 'node:crypto';

const root=resolve(fileURLToPath(new URL('../..',import.meta.url)));
const project='11111111-1111-4111-8111-111111111111';
let mf:Miniflare,db:D1Database,temp:string;
async function execSQL(sql:string){for(const statement of sql.replace(/--[^\r\n]*/g,'').split(/;\s*(?=(?:CREATE|INSERT)\b)/i).map(x=>x.trim()).filter(Boolean))await db.prepare(statement).run();}
async function org(id:string,tenant:string){await db.prepare('INSERT INTO tenants VALUES(?,?)').bind(tenant,tenant).run();await db.prepare('INSERT INTO organizations VALUES(?,?)').bind(id,tenant).run()}
async function installation(id:string,organization:string,status='active'){await db.prepare('INSERT INTO installation_keys VALUES(?,?,?, ?,0)').bind(id,organization,'',status).run()}
async function counts(){return db.prepare(`SELECT (SELECT count(*) FROM authority_project_claims) claims,(SELECT count(*) FROM authority_project_scope_evidence) evidence`).first()}

beforeAll(async()=>{temp=mkdtempSync(join(tmpdir(),'project-claim-'));mf=new Miniflare({...convertV4MiniflareOptions({modules:true,script:'export default {fetch(){return new Response("ok")}}',compatibilityDate:'2026-08-29',d1Databases:{DB:'claim'}}),resourcePersistencePath:temp});db=await mf.getD1Database('DB') as any;
 await execSQL(`CREATE TABLE tenants(id TEXT PRIMARY KEY,name TEXT);CREATE TABLE organizations(id TEXT PRIMARY KEY,tenant_id TEXT REFERENCES tenants(id));CREATE TABLE installation_keys(installation_id TEXT PRIMARY KEY,organization_id TEXT,public_key_raw TEXT,status TEXT,registered_at INTEGER);CREATE TABLE authority_project_scope_evidence(organization_id TEXT,project_id TEXT,revision TEXT,source_ref TEXT,evidence_kind TEXT,status TEXT,valid_until TEXT,PRIMARY KEY(organization_id,project_id));`);
 await execSQL(readFileSync(join(root,'backend/migrations/0016_authority_project_claims.sql'),'utf8'));
},60000);
beforeEach(async()=>{await db.prepare('DROP TRIGGER authority_project_claims_no_delete').run();for(const table of ['authority_project_scope_evidence','authority_project_claims','installation_keys','organizations','tenants'])await db.prepare(`DELETE FROM ${table}`).run();await db.prepare(`CREATE TRIGGER authority_project_claims_no_delete BEFORE DELETE ON authority_project_claims BEGIN SELECT RAISE(ABORT,'authority_project_claim_immutable'); END`).run();});
afterAll(async()=>{await mf.dispose();rmSync(temp,{recursive:true,force:true});});

describe('canonical project claim',()=>{
 it('claims once, replays across same-org installations, and exposes canonical evidence',async()=>{await org('org-a','tenant-a');await installation('i-a','org-a');await installation('i-b','org-a');const first=await claimProject(db,'org-a','i-a',project);expect(first.status).toBe('claimed');expect(first.tenantId).toBe('tenant-a');const replay=await claimProject(db,'org-a','i-b',project);expect(replay.status).toBe('already_claimed');expect(replay.claimedAt).toBe(first.claimedAt);expect(await db.prepare('SELECT evidence_kind,status FROM authority_project_scope_evidence WHERE project_id=?').bind(project).first()).toEqual({evidence_kind:'canonical',status:'active'});});
 it('rejects cross-organization and concurrent claims with one winner',async()=>{await org('org-a','tenant-a');await org('org-b','tenant-b');await installation('i-a','org-a');await installation('i-b','org-b');const settled=await Promise.allSettled([claimProject(db,'org-a','i-a',project),claimProject(db,'org-b','i-b',project)]);expect(settled.filter(x=>x.status==='fulfilled')).toHaveLength(1);expect(settled.filter(x=>x.status==='rejected')).toHaveLength(1);expect(await counts()).toEqual({claims:1,evidence:1});});
 it('serializes concurrent same-organization installations into one claim and one replay',async()=>{await org('org-a','tenant-a');await installation('i-a','org-a');await installation('i-b','org-a');const settled=await Promise.all([claimProject(db,'org-a','i-a',project),claimProject(db,'org-a','i-b',project)]);expect(settled.map(x=>x.status).sort()).toEqual(['already_claimed','claimed']);const rows=await db.prepare('SELECT installation_id,source_ref,claimed_at FROM authority_project_claims').all();expect(rows.results).toHaveLength(1);expect(await counts()).toEqual({claims:1,evidence:1});});
 it.each(['','UPPER','11111111-1111-1111-1111-111111111111',' 11111111-1111-4111-8111-111111111111'])('rejects invalid UUID %j without writes',async invalid=>{await org('org-a','tenant-a');await installation('i-a','org-a');await expect(claimProject(db,'org-a','i-a',invalid)).rejects.toMatchObject({status:400});expect(await counts()).toEqual({claims:0,evidence:0});});
 it('rejects missing org, inactive installation, and cross-org installation without writes',async()=>{await org('org-a','tenant-a');await org('org-b','tenant-b');await installation('revoked','org-a','revoked');await installation('foreign','org-b');await expect(claimProject(db,'missing','foreign',project)).rejects.toMatchObject({status:404});await expect(claimProject(db,'org-a','revoked',project)).rejects.toMatchObject({status:403});await expect(claimProject(db,'org-a','foreign',project)).rejects.toMatchObject({status:403});expect(await counts()).toEqual({claims:0,evidence:0});});
 it('rolls back the permanent claim when evidence insertion fails',async()=>{await org('org-a','tenant-a');await installation('i-a','org-a');await db.prepare(`CREATE TRIGGER fail_evidence BEFORE INSERT ON authority_project_scope_evidence BEGIN SELECT RAISE(ABORT,'fixture_failure'); END`).run();try{await expect(claimProject(db,'org-a','i-a',project)).rejects.toBeInstanceOf(ProjectClaimError)}finally{await db.prepare('DROP TRIGGER fail_evidence').run()}expect(await counts()).toEqual({claims:0,evidence:0});});
 it('never releases a UUID when operational evidence is expired or revoked',async()=>{await org('org-a','tenant-a');await org('org-b','tenant-b');await installation('i-a','org-a');await installation('i-b','org-b');await claimProject(db,'org-a','i-a',project);await db.prepare(`UPDATE authority_project_scope_evidence SET status='revoked',valid_until='2000-01-01T00:00:00Z'`).run();await expect(claimProject(db,'org-b','i-b',project)).rejects.toMatchObject({status:409});expect((await db.prepare('SELECT organization_id FROM authority_project_claims WHERE project_id=?').bind(project).first() as any).organization_id).toBe('org-a');});
 it('recreates absent evidence and renews expired evidence on same-organization replay',async()=>{await org('org-a','tenant-a');await installation('i-a','org-a');await installation('i-b','org-a');await claimProject(db,'org-a','i-a',project);await db.prepare('DELETE FROM authority_project_scope_evidence').run();await expect(claimProject(db,'org-a','i-b',project)).resolves.toMatchObject({status:'already_claimed',sourceRef:'installation:i-a'});await db.prepare(`UPDATE authority_project_scope_evidence SET valid_until='2000-01-01T00:00:00Z'`).run();await expect(claimProject(db,'org-a','i-b',project,new Date('2026-09-18T00:00:00Z'))).resolves.toMatchObject({status:'already_claimed'});expect(Date.parse((await db.prepare('SELECT valid_until FROM authority_project_scope_evidence').first<{valid_until:string}>())!.valid_until)).toBeGreaterThan(Date.parse('2026-09-18T00:00:00Z'));});
 it('does not reactivate revoked or overwrite contradictory evidence on replay',async()=>{await org('org-a','tenant-a');await installation('i-a','org-a');await claimProject(db,'org-a','i-a',project);await db.prepare(`UPDATE authority_project_scope_evidence SET status='revoked'`).run();await expect(claimProject(db,'org-a','i-a',project)).rejects.toMatchObject({message:'project_binding_revoked'});await db.prepare(`UPDATE authority_project_scope_evidence SET status='active',source_ref='installation:forged'`).run();await expect(claimProject(db,'org-a','i-a',project)).rejects.toMatchObject({message:'project_binding_inconsistent'});});
 it('never reports replay success when a matching UPDATE affects zero rows',async()=>{const now=new Date('2026-09-18T00:00:00Z');await org('org-a','tenant-a');await installation('i-a','org-a');await claimProject(db,'org-a','i-a',project,now);await db.prepare(`UPDATE authority_project_scope_evidence SET valid_until='2000-01-01T00:00:00Z'`).run();await db.prepare(`CREATE TRIGGER ignore_evidence_renewal BEFORE UPDATE ON authority_project_scope_evidence BEGIN SELECT RAISE(IGNORE); END`).run();try{await expect(claimProject(db,'org-a','i-a',project,now)).rejects.toMatchObject({message:'project_evidence_renewal_failed'})}finally{await db.prepare('DROP TRIGGER ignore_evidence_renewal').run()}});
 it('GET returns only current compatible evidence and never renews it',async()=>{const now=new Date('2026-09-18T00:00:00Z');await org('org-a','tenant-a');await installation('i-a','org-a');await claimProject(db,'org-a','i-a',project,now);const before=(await db.prepare('SELECT valid_until FROM authority_project_scope_evidence').first<{valid_until:string}>())!.valid_until;await expect(getProjectBinding(db,'org-a','i-a',project,now)).resolves.toMatchObject({status:'bound',organizationId:'org-a',tenantId:'tenant-a',projectId:project,validUntil:before});expect((await db.prepare('SELECT valid_until FROM authority_project_scope_evidence').first<{valid_until:string}>())!.valid_until).toBe(before);await db.prepare(`UPDATE authority_project_scope_evidence SET valid_until='2000-01-01T00:00:00Z'`).run();await expect(getProjectBinding(db,'org-a','i-a',project,now)).rejects.toMatchObject({message:'project_binding_expired'});await db.prepare(`UPDATE authority_project_scope_evidence SET status='revoked',valid_until='2099-01-01T00:00:00Z'`).run();await expect(getProjectBinding(db,'org-a','i-a',project,now)).rejects.toMatchObject({message:'project_binding_revoked'});});
 it('GET differentiates cross-organization and inconsistent claim/evidence',async()=>{const now=new Date('2026-09-18T00:00:00Z');await org('org-a','tenant-a');await org('org-b','tenant-b');await installation('i-a','org-a');await installation('i-b','org-b');await claimProject(db,'org-a','i-a',project,now);await expect(getProjectBinding(db,'org-b','i-b',project,now)).rejects.toMatchObject({message:'project_binding_cross_organization'});await db.prepare(`UPDATE authority_project_scope_evidence SET source_ref='installation:forged'`).run();await expect(getProjectBinding(db,'org-a','i-a',project,now)).rejects.toMatchObject({message:'project_binding_inconsistent'});});
 it('GET rejects a claim whose captured tenant no longer matches the organization',async()=>{const now=new Date('2026-09-18T00:00:00Z');await org('org-a','tenant-a');await db.prepare("INSERT INTO tenants VALUES('tenant-new','new')").run();await installation('i-a','org-a');await claimProject(db,'org-a','i-a',project,now);await db.prepare("UPDATE organizations SET tenant_id='tenant-new' WHERE id='org-a'").run();await expect(getProjectBinding(db,'org-a','i-a',project,now)).rejects.toMatchObject({message:'project_binding_inconsistent'});});
 it('route requires a valid path-bound installation signature and ignores forged body authority',async()=>{await org('org-a','tenant-a');const pair=generateKeyPairSync('ed25519');const raw=pair.publicKey.export({format:'der',type:'spki'}).subarray(-32);await db.prepare('INSERT INTO installation_keys VALUES(?,?,?,?,0)').bind('i-a','org-a',Buffer.from(raw).toString('base64'),'active').run();const path=`/v1/authority/projects/${project}/claim`,timestamp=new Date().toISOString(),payload=canonicalizeJson({installation_id:'i-a',organization_id:'org-a',method:'PUT',path,timestamp});const privateDer=pair.privateKey.export({format:'der',type:'pkcs8'});const privateBytes=new Uint8Array(privateDer);const signature=await signWithDomain('BLOOM-INSTALLATION-AUTH-v1',payload,privateBytes.buffer);const headers={'Content-Type':'application/json','X-Bloom-Installation-Id':'i-a','X-Bloom-Timestamp':timestamp,'X-Bloom-Signature':signature};const response=await app.request(`${path}?org=org-a`,{method:'PUT',headers,body:JSON.stringify({organization_id:'org-b',tenant_id:'tenant-b'})},{DB:db} as any);expect(response.status).toBe(201);expect(await response.json()).toMatchObject({organizationId:'org-a',tenantId:'tenant-a',projectId:project});const invalid=await app.request(`/v1/authority/projects/22222222-2222-4222-8222-222222222222/claim?org=org-a`,{method:'PUT',headers},{DB:db} as any);expect(invalid.status).toBe(401);expect(await counts()).toEqual({claims:1,evidence:1});});
 it('GET binding is independently path-signed and rejects a signature for another UUID',async()=>{await org('org-a','tenant-a');const pair=generateKeyPairSync('ed25519');const pub=pair.publicKey.export({format:'der',type:'spki'}).subarray(-32);await db.prepare('INSERT INTO installation_keys VALUES(?,?,?,?,0)').bind('i-a','org-a',Buffer.from(pub).toString('base64'),'active').run();await claimProject(db,'org-a','i-a',project);const sign=async(path:string)=>{const timestamp=new Date().toISOString();const payload=canonicalizeJson({installation_id:'i-a',organization_id:'org-a',method:'GET',path,timestamp});const key=new Uint8Array(pair.privateKey.export({format:'der',type:'pkcs8'}));return {'X-Bloom-Installation-Id':'i-a','X-Bloom-Timestamp':timestamp,'X-Bloom-Signature':await signWithDomain('BLOOM-INSTALLATION-AUTH-v1',payload,key.buffer)}};const path=`/v1/authority/projects/${project}/binding`;const response=await app.request(`${path}?org=org-a`,{headers:await sign(path)},{DB:db} as any);expect(response.status).toBe(200);expect(await response.json()).toMatchObject({status:'bound',projectId:project});const other='/v1/authority/projects/22222222-2222-4222-8222-222222222222/binding';expect((await app.request(`${other}?org=org-a`,{headers:await sign(path)},{DB:db} as any)).status).toBe(401);});
});

describe('0016 fail-closed migration',()=>{
 it.each([
  ['invalid source',`INSERT INTO authority_project_scope_evidence VALUES('org-a','${project}','1','bad','canonical','active','2099-01-01T00:00:00Z')`],
  ['missing installation',`INSERT INTO authority_project_scope_evidence VALUES('org-a','${project}','1','installation:missing','canonical','active','2099-01-01T00:00:00Z')`],
  ['inactive installation',`INSERT INTO installation_keys VALUES('i-a','org-a','','revoked',0);INSERT INTO authority_project_scope_evidence VALUES('org-a','${project}','1','installation:i-a','canonical','active','2099-01-01T00:00:00Z')`],
  ['cross organization installation',`INSERT INTO installation_keys VALUES('i-a','org-b','','active',0);INSERT INTO authority_project_scope_evidence VALUES('org-a','${project}','1','installation:i-a','canonical','active','2099-01-01T00:00:00Z')`],
  ['revision incompatible',`INSERT INTO installation_keys VALUES('i-a','org-a','','active',0);INSERT INTO authority_project_scope_evidence VALUES('org-a','${project}','2','installation:i-a','canonical','active','2099-01-01T00:00:00Z')`],
  ['tenant absent',`INSERT INTO organizations VALUES('org-c',NULL);INSERT INTO installation_keys VALUES('i-c','org-c','','active',0);INSERT INTO authority_project_scope_evidence VALUES('org-c','${project}','1','installation:i-c','canonical','active','2099-01-01T00:00:00Z')`],
  ['duplicate UUID across organizations',`INSERT INTO installation_keys VALUES('i-a','org-a','','active',0);INSERT INTO installation_keys VALUES('i-b','org-b','','active',0);INSERT INTO authority_project_scope_evidence VALUES('org-a','${project}','1','installation:i-a','canonical','active','2099-01-01T00:00:00Z');INSERT INTO authority_project_scope_evidence VALUES('org-b','${project}','1','installation:i-b','canonical','active','2099-01-01T00:00:00Z')`],
 ])('aborts before creating any claim for %s',async(_name,fixture)=>{const isolated=new Miniflare({...convertV4MiniflareOptions({modules:true,script:'export default {fetch(){return new Response("ok")}}',compatibilityDate:'2026-08-29',d1Databases:{DB:'migration'}})});try{const local=await isolated.getD1Database('DB') as any;await local.exec(`CREATE TABLE tenants(id TEXT PRIMARY KEY,name TEXT);CREATE TABLE organizations(id TEXT PRIMARY KEY,tenant_id TEXT REFERENCES tenants(id));CREATE TABLE installation_keys(installation_id TEXT PRIMARY KEY,organization_id TEXT,public_key_raw TEXT,status TEXT,registered_at INTEGER);CREATE TABLE authority_project_scope_evidence(organization_id TEXT,project_id TEXT,revision TEXT,source_ref TEXT,evidence_kind TEXT,status TEXT,valid_until TEXT,PRIMARY KEY(organization_id,project_id));INSERT INTO tenants VALUES('tenant-a','a');INSERT INTO tenants VALUES('tenant-b','b');INSERT INTO organizations VALUES('org-a','tenant-a');INSERT INTO organizations VALUES('org-b','tenant-b');${fixture}`);await expect(local.exec(readFileSync(join(root,'backend/migrations/0016_authority_project_claims.sql'),'utf8'))).rejects.toBeTruthy();await expect(local.prepare('SELECT count(*) FROM authority_project_claims').first()).rejects.toBeTruthy();}finally{await isolated.dispose();}},20000);
});
