import {afterAll,beforeAll,describe,expect,it} from "vitest";
import {Miniflare,convertV4MiniflareOptions} from "miniflare";
import {mkdtempSync,readFileSync,rmSync,writeFileSync} from "node:fs";import {spawnSync} from "node:child_process";
import {tmpdir} from "node:os";import {join,resolve} from "node:path";import {fileURLToPath} from "node:url";
import {persistEmission} from "../src/authority/emission-store";import {authoritySyncResponse} from "../src/authority/sync-route";
const root=resolve(fileURLToPath(new URL("../..",import.meta.url))),vector=JSON.parse(readFileSync(join(root,"docs/ROLES/fixtures/authority_interop_v1.json"),"utf8"));
let mf:Miniflare,db:D1Database,temp:string,env:any,org:string,installation:string;
async function migrate(file:string){const sql=readFileSync(join(root,"backend/migrations",file),"utf8").replace(/--[^\r\n]*/g,"").trim();for(const s of sql.split(/;\s*(?=CREATE\b)/i).filter(Boolean))await db.prepare(s).run();}
beforeAll(async()=>{
 temp=mkdtempSync(join(tmpdir(),"authority-sync-route-"));mf=new Miniflare({...convertV4MiniflareOptions({modules:true,script:'export default {fetch(){return new Response("ok")}}',compatibilityDate:"2026-08-29",d1Databases:{DB:"sync-route"}}),resourcePersistencePath:temp});db=await mf.getD1Database("DB") as any;
 await db.prepare("CREATE TABLE organizations(id TEXT PRIMARY KEY)").run();for(const f of ["0001_authority_snapshot.sql","0004_authority_emissions.sql"])await migrate(f);
 await db.prepare("CREATE TABLE installation_keys(installation_id TEXT PRIMARY KEY,organization_id TEXT,public_key_raw TEXT,status TEXT,registered_at INTEGER)").run();await db.prepare("CREATE TABLE authority_admin_requests(organization_id TEXT,request_id TEXT,PRIMARY KEY(organization_id,request_id))").run();await db.prepare("CREATE TABLE authority_admin_outbox(organization_id TEXT,event_id TEXT,authority_version TEXT,payload_json TEXT,created_at TEXT,delivered_at TEXT,PRIMARY KEY(organization_id,event_id),FOREIGN KEY(organization_id,event_id) REFERENCES authority_admin_requests(organization_id,request_id))").run();await migrate("0008_authority_sync.sql");
 org=vector.metadata.base.organization_id;installation=vector.metadata.base.audience.installation_ids[0];await db.prepare("INSERT INTO organizations VALUES(?)").bind(org).run();await db.prepare("INSERT INTO installation_keys VALUES(?,?,?,'active',0)").bind(installation,org,"key").run();const metadata=structuredClone(vector.metadata.base),state=structuredClone(vector.base_state);await persistEmission(db,{requestId:"fixture",expectedVersion:null,metadata,state,initialFixtureEvidence:{environment:"test",reference:"sync-route"}},{privateKeyPkcs8:Uint8Array.from(Buffer.from(vector.private_key_pkcs8_base64,"base64")).buffer,keyId:vector.key_id,allowTestFixtures:true});
 env={DB:db,AUTHORITY_SIGNING_KEY_PKCS8_B64:vector.private_key_pkcs8_base64,AUTHORITY_SIGNING_KEY_ID:vector.key_id,AUTHORITY_ISSUER:metadata.issuer,AUTHORITY_SYNC:{idFromName:(x:string)=>x,get:()=>({fetch:async()=>new Response("")})}};
},120000);
afterAll(async()=>{await mf.dispose();rmSync(temp,{recursive:true,force:true});});
describe("authoritative challenged pull",()=>{
 it("consumes a challenge once and exchanges the signed pull with Go",async()=>{const now=new Date("2026-09-08T12:05:00Z"),binding={organizationId:org,installationId:installation};const challengeResponse=await authoritySyncResponse(env,new Request(`https://backend.test/v1/authority/sync/challenge?org=${org}`,{method:"POST"}),binding,now);expect(challengeResponse.status).toBe(201);const challenge=(await challengeResponse.json() as any).challenge;const url=`https://backend.test/v1/authority/sync/pull?org=${org}&challenge=${encodeURIComponent(challenge)}&base_version=1`;const pull=await authoritySyncResponse(env,new Request(url),binding,now);expect(pull.status).toBe(200);const body:any=await pull.json();expect(body.snapshot.payload.kind).toBe("full");expect(body.current_check.payload.snapshot_digest).toBe(body.snapshot.integrity.digest);expect(body.current_check.payload.authority_version).toBe(body.snapshot.payload.authority_version);
  const artifact=join(temp,"sync-interop.json");writeFileSync(artifact,JSON.stringify({challenge,response:body,public_key:vector.public_key_base64url,key_id:vector.key_id,organization_id:org,installation_id:installation,issuer:vector.metadata.base.issuer,now:now.toISOString()}));const goRoot=resolve(root,"installer/nucleus");const run=spawnSync("go",["test","./internal/authority","-run","^TestSyncBackendArtifacts$","-count=1","-v"],{cwd:goRoot,encoding:"utf8",env:{...process.env,AUTHORITY_SYNC_ARTIFACT:artifact,GOPROXY:"off",GOCACHE:join(temp,"go-cache")}});expect(run.status,run.stdout+run.stderr).toBe(0);expect((await authoritySyncResponse(env,new Request(url),binding,now)).status).toBe(403);},120000);
 it("rejects an expired challenge",async()=>{const issued=new Date("2026-09-08T12:05:00Z"),binding={organizationId:org,installationId:installation};const r=await authoritySyncResponse(env,new Request(`https://x/v1/authority/sync/challenge?org=${org}`,{method:"POST"}),binding,issued);const c=(await r.json() as any).challenge;expect((await authoritySyncResponse(env,new Request(`https://x/v1/authority/sync/pull?org=${org}&challenge=${c}`),binding,new Date(issued.getTime()+120001))).status).toBe(403);});
});
