import {afterAll,beforeAll,describe,expect,it} from "vitest";
import {Miniflare,convertV4MiniflareOptions} from "miniflare";
import {mkdtempSync,readFileSync,rmSync} from "node:fs";import {tmpdir} from "node:os";import {join,resolve} from "node:path";import {fileURLToPath} from "node:url";
import {acknowledgeAuthorityNotice,authoritySyncMeasurements,claimAuthorityNotices,materializeAuthorityOutbox,recordAuthorityAcceptance} from "../src/authority/sync-store";
const root=resolve(fileURLToPath(new URL("../..",import.meta.url)));let mf:Miniflare,db:D1Database,temp:string;
async function migrate(file:string){const sql=readFileSync(join(root,"backend/migrations",file),"utf8").replace(/--[^\r\n]*/g,"").trim();for(const s of sql.split(/;\s*(?=CREATE\b)/i).filter(Boolean))await db.prepare(s).run();}
beforeAll(async()=>{temp=mkdtempSync(join(tmpdir(),"authority-sync-store-"));mf=new Miniflare({...convertV4MiniflareOptions({modules:true,script:'export default {fetch(){return new Response("ok")}}',compatibilityDate:"2026-08-29",d1Databases:{DB:"sync"}}),resourcePersistencePath:temp});db=await mf.getD1Database("DB") as unknown as D1Database;
 await db.prepare("CREATE TABLE organizations(id TEXT PRIMARY KEY)").run();await db.prepare("CREATE TABLE installation_keys(installation_id TEXT PRIMARY KEY,organization_id TEXT,public_key_raw TEXT,status TEXT,registered_at INTEGER)").run();
 await db.prepare("CREATE TABLE authority_admin_requests(organization_id TEXT,request_id TEXT,PRIMARY KEY(organization_id,request_id))").run();
 await db.prepare("CREATE TABLE authority_admin_outbox(organization_id TEXT,event_id TEXT,authority_version TEXT,payload_json TEXT,created_at TEXT,delivered_at TEXT,PRIMARY KEY(organization_id,event_id),FOREIGN KEY(organization_id,event_id) REFERENCES authority_admin_requests(organization_id,request_id))").run();
 await db.prepare("CREATE TABLE authority_emissions(organization_id TEXT,authority_version TEXT,metadata_json TEXT,PRIMARY KEY(organization_id,authority_version))").run();await migrate("0008_authority_sync.sql");},60000);
afterAll(async()=>{await mf.dispose();rmSync(temp,{recursive:true,force:true});});
async function seed(id:string){const org=`org-${id}`,created="2026-09-09T10:00:00.000Z";await db.prepare("INSERT INTO organizations VALUES(?)").bind(org).run();await db.prepare("INSERT INTO installation_keys VALUES(?,?,?,'active',0)").bind(`i-${id}`,org,"key").run();await db.prepare("INSERT INTO authority_admin_requests VALUES(?,?)").bind(org,id).run();await db.prepare("INSERT INTO authority_emissions VALUES(?,?,?)").bind(org,"2",JSON.stringify({audience:{installation_ids:[`i-${id}`]}})).run();await db.prepare("INSERT INTO authority_admin_outbox VALUES(?,?,?,?,?,NULL)").bind(org,id,"2",JSON.stringify({urgency:"standard",correlation_id:`c-${id}`}),created).run();return {org,installation:`i-${id}`};}
describe("durable authority sync store",()=>{
 it("retries an expired lease, deduplicates materialization and acknowledges once",async()=>{const x=await seed("retry");expect(await materializeAuthorityOutbox(db)).toBe(1);expect(await materializeAuthorityOutbox(db)).toBe(0);const first=(await claimAuthorityNotices(db,"w1",new Date("2026-09-09T10:00:01Z"),1000))[0];expect(first.attempts).toBe(1);expect(await acknowledgeAuthorityNotice(db,first,new Date("2026-09-09T10:00:03Z"))).toBe(false);const second=(await claimAuthorityNotices(db,"w2",new Date("2026-09-09T10:00:03Z"),1000))[0];expect(second.attempts).toBe(2);expect(await acknowledgeAuthorityNotice(db,second,new Date("2026-09-09T10:00:03.500Z"))).toBe(true);expect((await claimAuthorityNotices(db,"w3",new Date("2026-09-09T10:00:05Z"))).length).toBe(0);});
 it("keeps acceptance and hypothetical restriction measurements separate",async()=>{const x=await seed("metrics");await materializeAuthorityOutbox(db);await recordAuthorityAcceptance(db,x.org,x.installation,"2",new Date("2026-09-09T10:00:12Z"));const [m]=await authoritySyncMeasurements(db,x.org,x.installation);expect(m.commit_to_acceptance_ms).toBeGreaterThanOrEqual(11999);expect(m.commit_to_hypothetical_restriction_ms).toBeGreaterThanOrEqual(49999);expect(m.urgency).toBe("standard");});
});
