export type Item = { id: string; name: string; kind: string; project: string; position: [number, number, number]; color: string; description: string; detail: string };
export const items: Item[] = [
 {id:'identity',name:'Identidad',kind:'Domain',project:'Proyecto A',position:[-9,0,-3],color:'#50c9c3',description:'El lugar de las identidades y sus relaciones.',detail:'Una parcela del Proyecto A. Su forma es una hipótesis visual, no una frontera de autorización.'},
 {id:'access',name:'Acceso',kind:'Domain',project:'Proyecto A',position:[-3,0,3],color:'#50c9c3',description:'Las capacidades que cada persona puede utilizar.',detail:'Conectado con Identidad y Evidencia. Seguí sus Genes para explorar esas relaciones.'},
 {id:'evidence',name:'Evidencia',kind:'Domain',project:'Proyecto A',position:[-3,0,-7],color:'#50c9c3',description:'Los rastros que permiten comprender una decisión.',detail:'Aquí termina el recorrido simulado y aparece un Artifact.'},
 {id:'knowledge',name:'Conocimiento',kind:'Domain',project:'Proyecto B',position:[8,0,-4],color:'#ad9cf5',description:'Conocimiento que permanece después del trabajo.',detail:'Una parcela del Proyecto B conectada con Evidencia a través de un Gene transversal.'},
 {id:'delivery',name:'Entrega',kind:'Domain',project:'Proyecto B',position:[9,0,4],color:'#ad9cf5',description:'Resultados disponibles para otros desarrolladores.',detail:'El segundo Mandate conecta este territorio con Conocimiento.'},
 {id:'posture',name:'Preservar la trazabilidad',kind:'Posture',project:'Criterio compartido',position:[-5,4,-2],color:'#e9bd78',description:'Toda transformación debe conservar evidencia de su origen.',detail:'Postulates de ejemplo: registrar la procedencia; conservar las decisiones; vincular el resultado con su intención. La intensidad del campo representa Mass de manera exploratoria.'},
 {id:'posture2',name:'Conservar la autoría',kind:'Posture',project:'Criterio compartido',position:[8,3,-1],color:'#e9bd78',description:'El conocimiento conserva el vínculo con quien lo construyó.',detail:'Postulate de ejemplo: mantener la autoría al compartir un Artifact. La superposición es visual; este prototipo no calcula precedencia normativa.'},
 {id:'mandate',name:'Revisar acceso',kind:'Mandate',project:'Proyecto A',position:[-10,1,6],color:'#79dcac',description:'Revisar un cambio y conservar su evidencia.',detail:'Simulación: inspeccionar identidad → revisar acceso → producir evidencia. El ejecutor de demostración acompaña cada Intent. No hay ejecución real.'},
 {id:'mandate2',name:'Compartir resultado',kind:'Mandate',project:'Proyecto B',position:[12,1,7],color:'#79dcac',description:'Preparar conocimiento para su entrega.',detail:'Coordinado con Revisar acceso como ejemplo de Constellation. Se activa cuando el primer recorrido produce evidencia.'},
 {id:'artifact',name:'Registro de revisión',kind:'Artifact',project:'Proyecto A',position:[-3,1.3,-7],color:'#f0e8d7',description:'Evidencia producida por el recorrido simulado.',detail:'Documento de ejemplo\n\nOrigen: Revisar acceso.\nResultado: revisión registrada.\nAutoría: ejecutor de demostración.\nEstado: datos ficticios; ningún sistema real fue modificado.'}
];
export const genes = [['identity','access'],['access','evidence'],['evidence','identity'],['evidence','knowledge'],['knowledge','delivery']];
