interface Env {
  DB: D1Database;
  RELEASES: R2Bucket;
  MANDATES: R2Bucket;
  AUTHORITY_SYNC: DurableObjectNamespace;
  AUTHORITY_SIGNING_KEY_PKCS8_B64: string;
  AUTHORITY_SIGNING_KEY_ID: string;
  AUTHORITY_HUMAN_ORIGIN?: string;
  AUTHORITY_GITHUB_APP_CLIENT_ID?: string;
  AUTHORITY_GITHUB_APP_CLIENT_SECRET?: string;
  AUTHORITY_HUMAN_SESSION_KEY_B64?: string;
  AUTHORITY_ISSUER?: string;
  AUTHORITY_ROOT_KEY_ID?: string;
  AUTHORITY_ROOT_PUBLIC_KEY_B64URL?: string;
}
