#!/usr/bin/env bash
# Normalize PyInstaller .spec — strip absolute paths to portable placeholders.
# Keeps the spec functional; paths are regenerated by PyInstaller at build time.
HOME_ESC=$(echo "$HOME" | sed 's/[\/&]/\\&/g')

while IFS= read -r line || [[ -n "$line" ]]; do
  # Replace any absolute path rooted at $HOME with __HOME__
  line="${line//$HOME/__HOME__}"
  # Windows-style absolute paths: C:\Users\... or D:\...
  line=$(echo "$line" | sed "s|[A-Z]:\\\\[^'\"]*|__ABSPATH__|g")
  echo "$line"
done
