#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate __build__.py module with incremental BUILD_NUMBER.
This script is called during the build process to auto-increment the build counter.
"""

import sys
from pathlib import Path


def get_project_root() -> Path:
    """Get project root directory."""
    script_dir = Path(__file__).parent.resolve()  # build_deploy/
    return script_dir.parent.parent  # project root


def read_build_number(build_file: Path) -> int:
    """
    Read current build number from file.
    
    Args:
        build_file: Path to build_number.txt
        
    Returns:
        Current build number (0 if file doesn't exist)
    """
    if not build_file.exists():
        return 0
    
    try:
        content = build_file.read_text(encoding='utf-8').strip()
        return int(content)
    except (ValueError, FileNotFoundError):
        return 0


def write_build_number(build_file: Path, number: int) -> None:
    """
    Write build number to file.
    
    Args:
        build_file: Path to build_number.txt
        number: Build number to write
    """
    build_file.parent.mkdir(parents=True, exist_ok=True)
    build_file.write_text(str(number), encoding='utf-8')


def generate_build_module(output_path: Path, build_number: int) -> None:
    """
    Generate __build__.py module with BUILD_NUMBER constant.
    
    Args:
        output_path: Path where to create __build__.py
        build_number: Build number to embed
    """
    module_content = f'''"""
Auto-generated build information.
DO NOT EDIT MANUALLY - Generated by generate_build_module.py
"""

BUILD_NUMBER = {build_number}
'''
    
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(module_content, encoding='utf-8')


def main():
    """Main execution flow."""
    root = get_project_root()
    
    # Paths
    build_file = root / "brain" / "build_number.txt"
    build_module = root / "brain" / "__build__.py"
    
    # Read current build number
    current_build = read_build_number(build_file)
    
    # Increment
    new_build = current_build + 1
    
    # Update file
    write_build_number(build_file, new_build)
    
    # Generate module
    generate_build_module(build_module, new_build)
    
    print(f"✅ Build number incremented: {current_build} -> {new_build}")
    print(f"📝 Generated: {build_module}")
    print(f"📝 Updated: {build_file}")
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
