package gene

import (
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"nucleus/internal/core"
)

type authorizedFixture struct {
	FixtureClassification string       `json:"fixture_classification"`
	Synthetic             bool         `json:"synthetic"`
	ProductiveAuthority   bool         `json:"productive_authority"`
	ReusePolicy           string       `json:"reuse_policy"`
	ProjectID             string       `json:"project_id"`
	RepositoryID          string       `json:"repository_id"`
	Identity              Identity     `json:"identity"`
	Contribution          Contribution `json:"contribution"`
}

func fixtureRequest(t *testing.T, storeRoot string) MaterializeRequest {
	t.Helper()
	_, file, _, _ := runtime.Caller(0)
	raw, err := os.ReadFile(filepath.Join(filepath.Dir(file), "testdata", "authorized_first_gene.json"))
	if err != nil {
		t.Fatal(err)
	}
	var f authorizedFixture
	if err = json.Unmarshal(raw, &f); err != nil {
		t.Fatal(err)
	}
	if f.FixtureClassification != "test_only" || !f.Synthetic || f.ProductiveAuthority || f.ReusePolicy != "fixtures_only" {
		t.Fatal("fixture authority classification")
	}
	repo := filepath.Join(storeRoot, "synthetic-repository")
	if err = os.MkdirAll(filepath.Join(repo, "fixture"), 0700); err != nil {
		t.Fatal(err)
	}
	files := map[string]string{"file.txt": "synthetic file\n", "document.md": "# Synthetic document\n", "store_test.txt": "synthetic test\n"}
	for name, content := range files {
		if err = os.WriteFile(filepath.Join(repo, "fixture", name), []byte(content), 0600); err != nil {
			t.Fatal(err)
		}
	}
	return MaterializeRequest{ProjectID: f.ProjectID, ExpectedGeneration: 0, Identity: f.Identity, Contribution: f.Contribution, Repositories: map[string]string{f.RepositoryID: repo}}
}

func TestMaterializeFirstGeneAndReplay(t *testing.T) {
	root := t.TempDir()
	s := &Store{Root: root}
	req := fixtureRequest(t, root)
	first, err := s.Materialize(req)
	if err != nil {
		t.Fatal(err)
	}
	if first.Status != "committed" || first.PublishedGeneration != 1 {
		t.Fatalf("%#v", first)
	}
	replay, err := s.Materialize(req)
	if err != nil {
		t.Fatal(err)
	}
	if replay.Status != "replay" || replay.CanonicalCommitDigest != first.CanonicalCommitDigest || replay.RevisionDigest != first.RevisionDigest {
		t.Fatalf("%#v", replay)
	}
	head, _, err := s.loadHead(req.ProjectID)
	if err != nil {
		t.Fatal(err)
	}
	if head.Generation != 1 || head.Genes[req.Identity.GeneID].CurrentRevisionDigest != first.RevisionDigest {
		t.Fatalf("%#v", head)
	}
	// These literals are generated by the implementation from the authorized fixture and pin byte-level interoperability.
	if first.ContributionDigest != "sha256:503e6adaa6f4b76a773f0cc41af888c5c43309bfe3e50eee23b8e4b33f667ce4" || first.RevisionDigest != "sha256:0906f603e5e57f11b2cf9a6f6ac1f3d393dddd90bcfab5dde47407edf1affcd3" || first.CanonicalCommitDigest != "sha256:d855459b019483432ef4101eb48f4213d42568038539b09061dbd99e495ef55e" {
		t.Fatalf("digests contribution=%s revision=%s commit=%s", first.ContributionDigest, first.RevisionDigest, first.CanonicalCommitDigest)
	}
}

func TestContributionConflictAndCAS(t *testing.T) {
	root := t.TempDir()
	s := &Store{Root: root}
	req := fixtureRequest(t, root)
	if _, err := s.Materialize(req); err != nil {
		t.Fatal(err)
	}
	conflict := req
	conflict.Contribution.DeclaredFunction = "different"
	if _, err := s.Materialize(conflict); !errors.Is(err, ErrContributionIDConflict) {
		t.Fatalf("%v", err)
	}
	root2 := t.TempDir()
	s2 := &Store{Root: root2}
	req2 := fixtureRequest(t, root2)
	dir, _ := s2.initializeProject(req2.ProjectID)
	if _, err := s2.publishHead(dir, Head{SchemaVersion: SchemaVersion, ProjectID: req2.ProjectID, Generation: 1, Genes: map[string]GeneHead{}}); err != nil {
		t.Fatal(err)
	}
	if _, err := s2.Materialize(req2); !errors.Is(err, ErrProjectGeneration) {
		t.Fatalf("%v", err)
	}
}

func TestFixtureCannotClaimProductiveAuthority(t *testing.T) {
	root := t.TempDir()
	s := &Store{Root: root}
	req := fixtureRequest(t, root)
	req.Contribution.Ratification.Productive = true
	if _, err := s.Materialize(req); !errors.Is(err, ErrContributionNotRatified) {
		t.Fatal(err)
	}
}

func TestMaterializerUsesManagedGeneTelemetryStream(t *testing.T) {
	root := t.TempDir()
	logs := filepath.Join(root, "logs")
	logger, err := core.InitLogger(&core.Paths{LogsDir: logs, TelemetryDir: logs}, "GENE", true)
	if err != nil {
		t.Fatal(err)
	}
	s := &Store{Root: filepath.Join(root, "store"), Logger: logger}
	req := fixtureRequest(t, root)
	receipt, err := s.Materialize(req)
	if err != nil {
		_ = logger.Close()
		t.Fatal(err)
	}
	if _, err = s.Materialize(req); err != nil {
		_ = logger.Close()
		t.Fatal(err)
	}
	if err = logger.Close(); err != nil {
		t.Fatal(err)
	}

	telemetry, err := os.ReadFile(filepath.Join(logs, "telemetry.json"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(telemetry), `"nucleus_gene"`) {
		t.Fatalf("gene stream not registered: %s", telemetry)
	}
	if strings.Contains(string(telemetry), "GENE_CANONICAL_HEAD_PUBLISHED") {
		t.Fatal("event payload written directly to telemetry.json")
	}
	logFiles, err := filepath.Glob(filepath.Join(logs, "nucleus", "nucleus_gene_*.log"))
	if err != nil || len(logFiles) != 1 {
		t.Fatalf("logs=%v err=%v", logFiles, err)
	}
	logData, err := os.ReadFile(logFiles[0])
	if err != nil {
		t.Fatal(err)
	}
	for _, event := range []string{"GENE_MATERIALIZATION_STARTED", "GENE_CANONICAL_OBJECTS_INSTALLED", "GENE_CANONICAL_HEAD_PUBLISHED", "GENE_MATERIALIZATION_REPLAYED"} {
		if !strings.Contains(string(logData), event) {
			t.Fatalf("event %s missing from %s", event, logData)
		}
	}
	if !strings.Contains(string(logData), receipt.CanonicalCommitDigest) {
		t.Fatal("commit correlation missing from gene log")
	}
}
