package ionpump

// IonManifest corresponds to bootstrap-ions.json generated by build-bootstrap-ions.py
// and to the reconciliation manifests fetched from Batcave in Phase 6b.
type IonManifest struct {
	SchemaVersion string     `json:"schema_version"`
	GeneratedAt   string     `json:"generated_at"`
	Ions          []IonEntry `json:"ions"`
}

// IonEntry describes a single ion site to be reconciled.
type IonEntry struct {
	Domain      string `json:"domain"`
	Version     string `json:"version"`
	SHA256      string `json:"sha256"`
	ZipPath     string `json:"zip_path"`     // path to locally bundled ZIP; empty when DownloadURL is set
	DownloadURL string `json:"download_url"` // "" in bootstrap, real Batcave URL in Phase 6b
}

// ─────────────────────────────────────────────────────────────────────────────
// Response types — reconcile
// ─────────────────────────────────────────────────────────────────────────────

// ReconcileResult is the JSON response for `ion-pump reconcile`.
type ReconcileResult struct {
	Success       bool            `json:"success"`
	Manifest      string          `json:"manifest"`
	IonsProcessed int             `json:"ions_processed"`
	IonsSwapped   int             `json:"ions_swapped"`
	IonsSkipped   int             `json:"ions_skipped"`
	IonsFailed    int             `json:"ions_failed"`
	ForceSwap     bool            `json:"force_swap"`
	Results       []IonSwapResult `json:"results"`
}

// IonSwapResult is the per-domain entry inside ReconcileResult.
type IonSwapResult struct {
	Domain        string  `json:"domain"`
	Status        string  `json:"status"` // "swapped" | "skipped" | "failed"
	VersionBefore *string `json:"version_before"`
	VersionAfter  string  `json:"version_after"`
	BackupPath    *string `json:"backup_path"`
}

// ─────────────────────────────────────────────────────────────────────────────
// Response types — status
// ─────────────────────────────────────────────────────────────────────────────

// IonSiteStatus is the per-domain entry for `ion-pump status`.
type IonSiteStatus struct {
	Domain        string `json:"domain"`
	Version       string `json:"version"`
	SHA256        string `json:"sha256"`
	DeployedAt    string `json:"deployed_at"`
	Source        string `json:"source"`
	HasBackup     bool   `json:"has_backup"`
	ManifestValid bool   `json:"manifest_valid"`
}

// StatusResult is the JSON response for `ion-pump status`.
type StatusResult struct {
	IonSitesPath string          `json:"ionsites_path"`
	Ions         []IonSiteStatus `json:"ions"`
}

// ─────────────────────────────────────────────────────────────────────────────
// Response types — list
// ─────────────────────────────────────────────────────────────────────────────

// ManifestEntry is one entry in the `ion-pump list` response.
type ManifestEntry struct {
	Source        string `json:"source"`
	Path          string `json:"path"`
	IonsCount     int    `json:"ions_count"`
	SchemaVersion string `json:"schema_version"`
}

// ListResult is the JSON response for `ion-pump list`.
type ListResult struct {
	Manifests []ManifestEntry `json:"manifests"`
}

// ─────────────────────────────────────────────────────────────────────────────
// Response types — rollback
// ─────────────────────────────────────────────────────────────────────────────

// RollbackResult is the JSON response for `ion-pump rollback`.
type RollbackResult struct {
	Success        bool   `json:"success"`
	Domain         string `json:"domain"`
	VersionBefore  string `json:"version_before"`
	VersionAfter   string `json:"version_after"`
	BackupConsumed bool   `json:"backup_consumed"`
}

// ─────────────────────────────────────────────────────────────────────────────
// Response types — verify
// ─────────────────────────────────────────────────────────────────────────────

// IonVerifyResult is the per-domain entry for `ion-pump verify`.
type IonVerifyResult struct {
	Domain         string `json:"domain"`
	Valid          bool   `json:"valid"`
	ExpectedSHA256 string `json:"expected_sha256"`
	ActualSHA256   string `json:"actual_sha256"`
	FilesChecked   int    `json:"files_checked"`
	Error          string `json:"error,omitempty"`
}

// VerifyResult is the JSON response for `ion-pump verify`.
type VerifyResult struct {
	Valid        bool              `json:"valid"`
	IonsChecked  int               `json:"ions_checked"`
	IonsValid    int               `json:"ions_valid"`
	IonsInvalid  int               `json:"ions_invalid"`
	Results      []IonVerifyResult `json:"results"`
}
