package inspection

import (
	"archive/zip"
	"encoding/json"
	"fmt"
	"io"
	"strings"
)

const (
	blxMetaFile    = "cortex.meta.json"
	blxMaxMetaSize = 64 * 1024 // 64 KB safety cap
)

// CortexMeta represents the metadata embedded inside a .blx package.
// Schema matches cortex.meta.json generated by installer/cortex/build-cortex/package.py
type CortexMeta struct {
	Name             string `json:"name"`
	Version          string `json:"version"`
	BuildNumber      int    `json:"build_number"`
	BuildDate        string `json:"build_date"`
	ReleaseChannel   string `json:"release_channel"`    // "stable", "beta", "dev"
	MinChromeVersion string `json:"min_chrome_version"` // e.g. "120"
}

// ReadCortexMeta opens the .blx (ZIP), reads cortex.meta.json, parses it,
// and closes the archive before returning. Nothing is written to disk.
func ReadCortexMeta(blxPath string) (*CortexMeta, error) {
	r, err := zip.OpenReader(blxPath)
	if err != nil {
		return nil, fmt.Errorf("failed to open .blx archive: %w", err)
	}
	defer r.Close()

	var metaFile *zip.File
	for _, f := range r.File {
		if f.Name == blxMetaFile {
			metaFile = f
			break
		}
	}
	if metaFile == nil {
		return nil, fmt.Errorf("%s not found inside .blx archive", blxMetaFile)
	}

	if metaFile.UncompressedSize64 > blxMaxMetaSize {
		return nil, fmt.Errorf("%s exceeds max allowed size (%d bytes)", blxMetaFile, blxMaxMetaSize)
	}

	rc, err := metaFile.Open()
	if err != nil {
		return nil, fmt.Errorf("failed to open %s inside archive: %w", blxMetaFile, err)
	}
	defer rc.Close()

	data, err := io.ReadAll(io.LimitReader(rc, blxMaxMetaSize))
	if err != nil {
		return nil, fmt.Errorf("failed to read %s: %w", blxMetaFile, err)
	}

	var meta CortexMeta
	if err := json.Unmarshal(data, &meta); err != nil {
		return nil, fmt.Errorf("failed to parse %s: %w", blxMetaFile, err)
	}
	if meta.Version == "" {
		return nil, fmt.Errorf("%s is missing required field: version", blxMetaFile)
	}

	return &meta, nil
}

// applyCortexMeta enriches a ManagedBinary with data extracted from CortexMeta.
func applyCortexMeta(binary *ManagedBinary, meta *CortexMeta) {
	binary.Version      = meta.Version
	binary.BuildNumber  = meta.BuildNumber
	binary.Status       = "healthy"
	binary.CortexMeta   = meta
}

// isCortexBinary returns true if the path points to a .blx file.
func isCortexBinary(path string) bool {
	return strings.HasSuffix(strings.ToLower(path), ".blx")
}