// Auto-generated by build.sh - DO NOT EDIT MANUALLY
#ifndef BUILD_INFO_H
#define BUILD_INFO_H

#define BUILD_NUMBER 151
#define BUILD_DATE "2026-06-02"
#define BUILD_TIME "19:25:07"
#define VERSION_STRING "2.2.0"

#endif // BUILD_INFO_H
