// Auto-generated by build.sh - DO NOT EDIT MANUALLY
#ifndef BUILD_INFO_H
#define BUILD_INFO_H

#define BUILD_NUMBER 0
#define BUILD_DATE "1970-01-01"
#define BUILD_TIME "00:00:00"
#define VERSION_STRING "2.2.0"

#endif // BUILD_INFO_H
