// Auto-generated by build.sh - DO NOT EDIT MANUALLY
#ifndef BUILD_INFO_H
#define BUILD_INFO_H

#define BUILD_NUMBER 147
#define BUILD_DATE "2026-05-30"
#define BUILD_TIME "13:46:43"
#define VERSION_STRING "2.2.0"

#endif // BUILD_INFO_H
