"""
Auto-generated build information.
DO NOT EDIT MANUALLY - regenerated by installer/aitap/scripts/build.py on
every build, from the BLOOM_BUILD_NUMBER env var injected by build-all.py.
"""

BUILD_NUMBER = 12
BUILD_DATE = "2026-10-06"
BUILD_TIME = "13:02:11"
