"""
Explicit command loader for frozen executables.
Este archivo carga todos los comandos cuando Brain corre como .exe

AUTO-GENERATED by generate_command_loader.py
"""
from brain.cli.registry import CommandRegistry


def load_all_commands_explicit() -> CommandRegistry:
    """
    Carga todos los comandos explícitamente para PyInstaller.
    
    Este método se usa SOLO cuando Brain corre como ejecutable empaquetado.
    En desarrollo, se usa el auto-discovery normal.
    
    Returns:
        CommandRegistry con todos los comandos cargados
    """
    registry = CommandRegistry()
    
    # =================================================================
    # CONTEXT
    # =================================================================
    try:
        from brain.commands.context.generate import ContextGenerateCommand
        registry.register(ContextGenerateCommand())
    except ImportError as e:
        print(f"Warning: Could not load ContextGenerateCommand: {e}")
    
    # =================================================================
    # EXTENSION
    # =================================================================
    try:
        from brain.commands.extension.backups import BackupsCommand
        registry.register(BackupsCommand())
    except ImportError as e:
        print(f"Warning: Could not load BackupsCommand: {e}")
    
    try:
        from brain.commands.extension.install import InstallCommand
        registry.register(InstallCommand())
    except ImportError as e:
        print(f"Warning: Could not load InstallCommand: {e}")
    
    try:
        from brain.commands.extension.update import UpdateCommand
        registry.register(UpdateCommand())
    except ImportError as e:
        print(f"Warning: Could not load UpdateCommand: {e}")
    
    try:
        from brain.commands.extension.verify import VerifyCommand
        registry.register(VerifyCommand())
    except ImportError as e:
        print(f"Warning: Could not load VerifyCommand: {e}")
    
    # =================================================================
    # FILESYSTEM
    # =================================================================
    try:
        from brain.commands.filesystem.compress import CompressCommand
        registry.register(CompressCommand())
    except ImportError as e:
        print(f"Warning: Could not load CompressCommand: {e}")
    
    try:
        from brain.commands.filesystem.compress import ExtractCommand
        registry.register(ExtractCommand())
    except ImportError as e:
        print(f"Warning: Could not load ExtractCommand: {e}")
    
    try:
        from brain.commands.filesystem.tree import TreeCommand
        registry.register(TreeCommand())
    except ImportError as e:
        print(f"Warning: Could not load TreeCommand: {e}")
    
    # =================================================================
    # GEMINI
    # =================================================================
    try:
        from brain.commands.gemini.keys_add import GeminiKeysAddCommand
        registry.register(GeminiKeysAddCommand())
    except ImportError as e:
        print(f"Warning: Could not load GeminiKeysAddCommand: {e}")
    
    try:
        from brain.commands.gemini.keys_delete import GeminiKeysDeleteCommand
        registry.register(GeminiKeysDeleteCommand())
    except ImportError as e:
        print(f"Warning: Could not load GeminiKeysDeleteCommand: {e}")
    
    try:
        from brain.commands.gemini.keys_list import GeminiKeysListCommand
        registry.register(GeminiKeysListCommand())
    except ImportError as e:
        print(f"Warning: Could not load GeminiKeysListCommand: {e}")
    
    try:
        from brain.commands.gemini.keys_stats import GeminiKeysStatsCommand
        registry.register(GeminiKeysStatsCommand())
    except ImportError as e:
        print(f"Warning: Could not load GeminiKeysStatsCommand: {e}")
    
    try:
        from brain.commands.gemini.keys_validate import GeminiKeysValidateCommand
        registry.register(GeminiKeysValidateCommand())
    except ImportError as e:
        print(f"Warning: Could not load GeminiKeysValidateCommand: {e}")
    
    # =================================================================
    # GITHUB
    # =================================================================
    try:
        from brain.commands.github.auth import GithubAuthCommand
        registry.register(GithubAuthCommand())
    except ImportError as e:
        print(f"Warning: Could not load GithubAuthCommand: {e}")
    
    try:
        from brain.commands.github.auth_login import GithubAuthLoginCommand
        registry.register(GithubAuthLoginCommand())
    except ImportError as e:
        print(f"Warning: Could not load GithubAuthLoginCommand: {e}")
    
    try:
        from brain.commands.github.auth_logout import GithubAuthLogoutCommand
        registry.register(GithubAuthLogoutCommand())
    except ImportError as e:
        print(f"Warning: Could not load GithubAuthLogoutCommand: {e}")
    
    try:
        from brain.commands.github.auth_status import GithubAuthStatusCommand
        registry.register(GithubAuthStatusCommand())
    except ImportError as e:
        print(f"Warning: Could not load GithubAuthStatusCommand: {e}")
    
    try:
        from brain.commands.github.clone import GithubCloneCommand
        registry.register(GithubCloneCommand())
    except ImportError as e:
        print(f"Warning: Could not load GithubCloneCommand: {e}")
    
    try:
        from brain.commands.github.orgs import GithubOrgsCommand
        registry.register(GithubOrgsCommand())
    except ImportError as e:
        print(f"Warning: Could not load GithubOrgsCommand: {e}")
    
    try:
        from brain.commands.github.orgs_list import GithubOrgsListCommand
        registry.register(GithubOrgsListCommand())
    except ImportError as e:
        print(f"Warning: Could not load GithubOrgsListCommand: {e}")
    
    try:
        from brain.commands.github.repos import GithubReposCommand
        registry.register(GithubReposCommand())
    except ImportError as e:
        print(f"Warning: Could not load GithubReposCommand: {e}")
    
    try:
        from brain.commands.github.repos_list import GithubReposListCommand
        registry.register(GithubReposListCommand())
    except ImportError as e:
        print(f"Warning: Could not load GithubReposListCommand: {e}")
    
    # =================================================================
    # HEALTH
    # =================================================================
    try:
        from brain.commands.health.dev_check import HealthDevCheckCommand
        registry.register(HealthDevCheckCommand())
    except ImportError as e:
        print(f"Warning: Could not load HealthDevCheckCommand: {e}")
    
    try:
        from brain.commands.health.full_stack import HealthFullStackCommand
        registry.register(HealthFullStackCommand())
    except ImportError as e:
        print(f"Warning: Could not load HealthFullStackCommand: {e}")
    
    try:
        from brain.commands.health.native_ping import HealthNativePingCommand
        registry.register(HealthNativePingCommand())
    except ImportError as e:
        print(f"Warning: Could not load HealthNativePingCommand: {e}")
    
    try:
        from brain.commands.health.onboarding_status import HealthOnboardingStatusCommand
        registry.register(HealthOnboardingStatusCommand())
    except ImportError as e:
        print(f"Warning: Could not load HealthOnboardingStatusCommand: {e}")
    
    try:
        from brain.commands.health.websocket_status import HealthWebSocketStatusCommand
        registry.register(HealthWebSocketStatusCommand())
    except ImportError as e:
        print(f"Warning: Could not load HealthWebSocketStatusCommand: {e}")
    
    # =================================================================
    # INTENT
    # =================================================================
    try:
        from brain.commands.intent.add_turn import AddTurnCommand
        registry.register(AddTurnCommand())
    except ImportError as e:
        print(f"Warning: Could not load AddTurnCommand: {e}")
    
    try:
        from brain.commands.intent.build_payload import BuildPayloadCommand
        registry.register(BuildPayloadCommand())
    except ImportError as e:
        print(f"Warning: Could not load BuildPayloadCommand: {e}")
    
    try:
        from brain.commands.intent.create import CreateCommand
        registry.register(CreateCommand())
    except ImportError as e:
        print(f"Warning: Could not load CreateCommand: {e}")
    
    try:
        from brain.commands.intent.delete import DeleteCommand
        registry.register(DeleteCommand())
    except ImportError as e:
        print(f"Warning: Could not load DeleteCommand: {e}")
    
    try:
        from brain.commands.intent.download import DownloadCommand
        registry.register(DownloadCommand())
    except ImportError as e:
        print(f"Warning: Could not load DownloadCommand: {e}")
    
    try:
        from brain.commands.intent.finalize import FinalizeCommand
        registry.register(FinalizeCommand())
    except ImportError as e:
        print(f"Warning: Could not load FinalizeCommand: {e}")
    
    try:
        from brain.commands.intent.get import GetCommand
        registry.register(GetCommand())
    except ImportError as e:
        print(f"Warning: Could not load GetCommand: {e}")
    
    try:
        from brain.commands.intent.hydrate import HydrateCommand
        registry.register(HydrateCommand())
    except ImportError as e:
        print(f"Warning: Could not load HydrateCommand: {e}")
    
    try:
        from brain.commands.intent.list import ListCommand
        registry.register(ListCommand())
    except ImportError as e:
        print(f"Warning: Could not load ListCommand: {e}")
    
    try:
        from brain.commands.intent.lock import LockCommand
        registry.register(LockCommand())
    except ImportError as e:
        print(f"Warning: Could not load LockCommand: {e}")
    
    try:
        from brain.commands.intent.merge import MergeCommand
        registry.register(MergeCommand())
    except ImportError as e:
        print(f"Warning: Could not load MergeCommand: {e}")
    
    try:
        from brain.commands.intent.parse import IntentParseCommand
        registry.register(IntentParseCommand())
    except ImportError as e:
        print(f"Warning: Could not load IntentParseCommand: {e}")
    
    try:
        from brain.commands.intent.plan import PlanCommand
        registry.register(PlanCommand())
    except ImportError as e:
        print(f"Warning: Could not load PlanCommand: {e}")
    
    try:
        from brain.commands.intent.recover import RecoverCommand
        registry.register(RecoverCommand())
    except ImportError as e:
        print(f"Warning: Could not load RecoverCommand: {e}")
    
    try:
        from brain.commands.intent.stage import StageCommand
        registry.register(StageCommand())
    except ImportError as e:
        print(f"Warning: Could not load StageCommand: {e}")
    
    try:
        from brain.commands.intent.submit import SubmitCommand
        registry.register(SubmitCommand())
    except ImportError as e:
        print(f"Warning: Could not load SubmitCommand: {e}")
    
    try:
        from brain.commands.intent.unlock import UnlockCommand
        registry.register(UnlockCommand())
    except ImportError as e:
        print(f"Warning: Could not load UnlockCommand: {e}")
    
    try:
        from brain.commands.intent.update import UpdateCommand
        registry.register(UpdateCommand())
    except ImportError as e:
        print(f"Warning: Could not load UpdateCommand: {e}")
    
    try:
        from brain.commands.intent.validate import ValidateCommand
        registry.register(ValidateCommand())
    except ImportError as e:
        print(f"Warning: Could not load ValidateCommand: {e}")
    
    # =================================================================
    # NUCLEUS
    # =================================================================
    try:
        from brain.commands.nucleus.create import NucleusCreateCommand
        registry.register(NucleusCreateCommand())
    except ImportError as e:
        print(f"Warning: Could not load NucleusCreateCommand: {e}")
    
    try:
        from brain.commands.nucleus.create_exp_intent import NucleusCreateExpIntentCommand
        registry.register(NucleusCreateExpIntentCommand())
    except ImportError as e:
        print(f"Warning: Could not load NucleusCreateExpIntentCommand: {e}")
    
    try:
        from brain.commands.nucleus.delete import NucleusDeleteCommand
        registry.register(NucleusDeleteCommand())
    except ImportError as e:
        print(f"Warning: Could not load NucleusDeleteCommand: {e}")
    
    try:
        from brain.commands.nucleus.exp_discovery_turn import NucleusExpDiscoveryTurnCommand
        registry.register(NucleusExpDiscoveryTurnCommand())
    except ImportError as e:
        print(f"Warning: Could not load NucleusExpDiscoveryTurnCommand: {e}")
    
    try:
        from brain.commands.nucleus.exp_export_findings import NucleusExpExportFindingsCommand
        registry.register(NucleusExpExportFindingsCommand())
    except ImportError as e:
        print(f"Warning: Could not load NucleusExpExportFindingsCommand: {e}")
    
    try:
        from brain.commands.nucleus.get import NucleusGetCommand
        registry.register(NucleusGetCommand())
    except ImportError as e:
        print(f"Warning: Could not load NucleusGetCommand: {e}")
    
    try:
        from brain.commands.nucleus.info import ProjectInfoCommand
        registry.register(ProjectInfoCommand())
    except ImportError as e:
        print(f"Warning: Could not load ProjectInfoCommand: {e}")
    
    try:
        from brain.commands.nucleus.link import NucleusLinkCommand
        registry.register(NucleusLinkCommand())
    except ImportError as e:
        print(f"Warning: Could not load NucleusLinkCommand: {e}")
    
    try:
        from brain.commands.nucleus.list import NucleusListCommand
        registry.register(NucleusListCommand())
    except ImportError as e:
        print(f"Warning: Could not load NucleusListCommand: {e}")
    
    try:
        from brain.commands.nucleus.list_projects import NucleusListProjectsCommand
        registry.register(NucleusListProjectsCommand())
    except ImportError as e:
        print(f"Warning: Could not load NucleusListProjectsCommand: {e}")
    
    try:
        from brain.commands.nucleus.onboarding_complete import NucleusOnboardingCompleteCommand
        registry.register(NucleusOnboardingCompleteCommand())
    except ImportError as e:
        print(f"Warning: Could not load NucleusOnboardingCompleteCommand: {e}")
    
    try:
        from brain.commands.nucleus.onboarding_status import NucleusOnboardingStatusCommand
        registry.register(NucleusOnboardingStatusCommand())
    except ImportError as e:
        print(f"Warning: Could not load NucleusOnboardingStatusCommand: {e}")
    
    try:
        from brain.commands.nucleus.project_info import NucleusProjectInfoCommand
        registry.register(NucleusProjectInfoCommand())
    except ImportError as e:
        print(f"Warning: Could not load NucleusProjectInfoCommand: {e}")
    
    try:
        from brain.commands.nucleus.status import NucleusStatusCommand
        registry.register(NucleusStatusCommand())
    except ImportError as e:
        print(f"Warning: Could not load NucleusStatusCommand: {e}")
    
    try:
        from brain.commands.nucleus.sync import NucleusSyncCommand
        registry.register(NucleusSyncCommand())
    except ImportError as e:
        print(f"Warning: Could not load NucleusSyncCommand: {e}")
    
    # =================================================================
    # PROFILE
    # =================================================================
    try:
        from brain.commands.profile.accounts import AccountsLinkCommand
        registry.register(AccountsLinkCommand())
    except ImportError as e:
        print(f"Warning: Could not load AccountsLinkCommand: {e}")
    
    try:
        from brain.commands.profile.accounts import AccountsUnlinkCommand
        registry.register(AccountsUnlinkCommand())
    except ImportError as e:
        print(f"Warning: Could not load AccountsUnlinkCommand: {e}")
    
    try:
        from brain.commands.profile.profiles import ProfilesAccountsRegisterCommand
        registry.register(ProfilesAccountsRegisterCommand())
    except ImportError as e:
        print(f"Warning: Could not load ProfilesAccountsRegisterCommand: {e}")
    
    try:
        from brain.commands.profile.profiles import ProfilesAccountsRemoveCommand
        registry.register(ProfilesAccountsRemoveCommand())
    except ImportError as e:
        print(f"Warning: Could not load ProfilesAccountsRemoveCommand: {e}")
    
    try:
        from brain.commands.profile.profiles import ProfilesCreateCommand
        registry.register(ProfilesCreateCommand())
    except ImportError as e:
        print(f"Warning: Could not load ProfilesCreateCommand: {e}")
    
    try:
        from brain.commands.profile.profiles import ProfilesDestroyCommand
        registry.register(ProfilesDestroyCommand())
    except ImportError as e:
        print(f"Warning: Could not load ProfilesDestroyCommand: {e}")
    
    try:
        from brain.commands.profile.profiles import ProfilesLaunchCommand
        registry.register(ProfilesLaunchCommand())
    except ImportError as e:
        print(f"Warning: Could not load ProfilesLaunchCommand: {e}")
    
    try:
        from brain.commands.profile.profiles import ProfilesLinkCommand
        registry.register(ProfilesLinkCommand())
    except ImportError as e:
        print(f"Warning: Could not load ProfilesLinkCommand: {e}")
    
    try:
        from brain.commands.profile.profiles import ProfilesListCommand
        registry.register(ProfilesListCommand())
    except ImportError as e:
        print(f"Warning: Could not load ProfilesListCommand: {e}")
    
    try:
        from brain.commands.profile.profiles import ProfilesUnlinkCommand
        registry.register(ProfilesUnlinkCommand())
    except ImportError as e:
        print(f"Warning: Could not load ProfilesUnlinkCommand: {e}")
    
    # =================================================================
    # PROJECT
    # =================================================================
    try:
        from brain.commands.project.add import ProjectAddCommand
        registry.register(ProjectAddCommand())
    except ImportError as e:
        print(f"Warning: Could not load ProjectAddCommand: {e}")
    
    try:
        from brain.commands.project.clone_and_add import CloneAndAddCommand
        registry.register(CloneAndAddCommand())
    except ImportError as e:
        print(f"Warning: Could not load CloneAndAddCommand: {e}")
    
    try:
        from brain.commands.project.detect import ProjectDetectCommand
        registry.register(ProjectDetectCommand())
    except ImportError as e:
        print(f"Warning: Could not load ProjectDetectCommand: {e}")
    
    try:
        from brain.commands.project.load import ProjectLoadCommand
        registry.register(ProjectLoadCommand())
    except ImportError as e:
        print(f"Warning: Could not load ProjectLoadCommand: {e}")
    
    try:
        from brain.commands.project.nucleus import NucleusCommand
        registry.register(NucleusCommand())
    except ImportError as e:
        print(f"Warning: Could not load NucleusCommand: {e}")
    
    # =================================================================
    # RUNTIME
    # =================================================================
    try:
        from brain.commands.runtime.run import RuntimeRunCommand
        registry.register(RuntimeRunCommand())
    except ImportError as e:
        print(f"Warning: Could not load RuntimeRunCommand: {e}")
    
    # =================================================================
    # SERVICE
    # =================================================================
    try:
        from brain.commands.service.service import ServiceCommand
        registry.register(ServiceCommand())
    except ImportError as e:
        print(f"Warning: Could not load ServiceCommand: {e}")
    
    # =================================================================
    # SYNAPSE
    # =================================================================
    try:
        from brain.commands.synapse.synapse_host_cli import SynapseHostCommand
        registry.register(SynapseHostCommand())
    except ImportError as e:
        print(f"Warning: Could not load SynapseHostCommand: {e}")
    
    # =================================================================
    # SYSTEM
    # =================================================================
    try:
        from brain.commands.system.info import SystemInfoCommand
        registry.register(SystemInfoCommand())
    except ImportError as e:
        print(f"Warning: Could not load SystemInfoCommand: {e}")
    
    try:
        from brain.commands.system.info import SystemPathCommand
        registry.register(SystemPathCommand())
    except ImportError as e:
        print(f"Warning: Could not load SystemPathCommand: {e}")
    
    try:
        from brain.commands.system.info import SystemVersionCommand
        registry.register(SystemVersionCommand())
    except ImportError as e:
        print(f"Warning: Could not load SystemVersionCommand: {e}")
    
    # =================================================================
    # TWITTER
    # =================================================================
    try:
        from brain.commands.twitter.auth import TwitterAuthCommand
        registry.register(TwitterAuthCommand())
    except ImportError as e:
        print(f"Warning: Could not load TwitterAuthCommand: {e}")
    
    return registry


def get_hiddenimports_list():
    """
    Lista de módulos para agregar a hiddenimports en el .spec file.
    
    Returns:
        Lista de strings con los import paths
    """
    return [
        'brain.commands.context.generate',
        'brain.commands.extension.backups',
        'brain.commands.extension.install',
        'brain.commands.extension.update',
        'brain.commands.extension.verify',
        'brain.commands.filesystem.compress',
        'brain.commands.filesystem.compress',
        'brain.commands.filesystem.tree',
        'brain.commands.gemini.keys_add',
        'brain.commands.gemini.keys_delete',
        'brain.commands.gemini.keys_list',
        'brain.commands.gemini.keys_stats',
        'brain.commands.gemini.keys_validate',
        'brain.commands.github.auth',
        'brain.commands.github.auth_login',
        'brain.commands.github.auth_logout',
        'brain.commands.github.auth_status',
        'brain.commands.github.clone',
        'brain.commands.github.orgs',
        'brain.commands.github.orgs_list',
        'brain.commands.github.repos',
        'brain.commands.github.repos_list',
        'brain.commands.health.dev_check',
        'brain.commands.health.full_stack',
        'brain.commands.health.native_ping',
        'brain.commands.health.onboarding_status',
        'brain.commands.health.websocket_status',
        'brain.commands.intent.add_turn',
        'brain.commands.intent.build_payload',
        'brain.commands.intent.create',
        'brain.commands.intent.delete',
        'brain.commands.intent.download',
        'brain.commands.intent.finalize',
        'brain.commands.intent.get',
        'brain.commands.intent.hydrate',
        'brain.commands.intent.list',
        'brain.commands.intent.lock',
        'brain.commands.intent.merge',
        'brain.commands.intent.parse',
        'brain.commands.intent.plan',
        'brain.commands.intent.recover',
        'brain.commands.intent.stage',
        'brain.commands.intent.submit',
        'brain.commands.intent.unlock',
        'brain.commands.intent.update',
        'brain.commands.intent.validate',
        'brain.commands.nucleus.create',
        'brain.commands.nucleus.create_exp_intent',
        'brain.commands.nucleus.delete',
        'brain.commands.nucleus.exp_discovery_turn',
        'brain.commands.nucleus.exp_export_findings',
        'brain.commands.nucleus.get',
        'brain.commands.nucleus.info',
        'brain.commands.nucleus.link',
        'brain.commands.nucleus.list',
        'brain.commands.nucleus.list_projects',
        'brain.commands.nucleus.onboarding_complete',
        'brain.commands.nucleus.onboarding_status',
        'brain.commands.nucleus.project_info',
        'brain.commands.nucleus.status',
        'brain.commands.nucleus.sync',
        'brain.commands.profile.accounts',
        'brain.commands.profile.accounts',
        'brain.commands.profile.profiles',
        'brain.commands.profile.profiles',
        'brain.commands.profile.profiles',
        'brain.commands.profile.profiles',
        'brain.commands.profile.profiles',
        'brain.commands.profile.profiles',
        'brain.commands.profile.profiles',
        'brain.commands.profile.profiles',
        'brain.commands.project.add',
        'brain.commands.project.clone_and_add',
        'brain.commands.project.detect',
        'brain.commands.project.load',
        'brain.commands.project.nucleus',
        'brain.commands.runtime.run',
        'brain.commands.service.service',
        'brain.commands.synapse.synapse_host_cli',
        'brain.commands.system.info',
        'brain.commands.system.info',
        'brain.commands.system.info',
        'brain.commands.twitter.auth',
    ]
