"""
Discovery Page Generator - Extension validation interface.
Creates ONLY static HTML/CSS/JS assets (CSP compliant).

IMPORTANT: Configuration files (discovery.synapse.config.js, landing.synapse.config.js)
are now generated by Sentinel (Go) during the launch sequence. This module ONLY
handles static asset deployment.

CHANGELOG v3.0:
- Removed _generate_synapse_config() - delegated to Sentinel
- Removed _generate_launch_id() - delegated to Sentinel  
- Removed update_discovery_config() - config updates via Sentinel
- Simplified to pure static asset manager
"""

import shutil
from pathlib import Path
from typing import Dict, Any
from brain.shared.logger import get_logger

logger = get_logger(__name__)


def generate_discovery_page(target_ext_dir: Path, profile_data: Dict[str, Any]) -> None:
    """
    Generates ONLY static discovery page assets inside the extension directory.
    
    Configuration files (*.synapse.config.js) are generated by Sentinel during
    the launch sequence with proper launch_id and session identity.
    
    Args:
        target_ext_dir: Path to profiles/[UUID]/extension/
        profile_data: Dict with profile metadata (for logging purposes only)
    """
    logger.info(f"🔧 Desplegando assets estáticos de discovery para: {profile_data.get('alias')}")
    
    discovery_dir = target_ext_dir / "discovery"
    discovery_dir.mkdir(parents=True, exist_ok=True)
    
    # Deploy static files only
    _copy_static_assets(discovery_dir)
    
    logger.info(f"  ✅ Assets estáticos desplegados en: {discovery_dir}")
    logger.info(f"  ℹ️  Los archivos de configuración serán generados por Sentinel durante el launch")


def _copy_static_assets(discovery_dir: Path) -> None:
    """
    Copies static HTML, CSS, and JS from templates WITHOUT modifications.
    Does NOT include configuration files - those are Sentinel's responsibility.
    """
    logger.debug("  📋 Copiando assets estáticos...")
    
    template_dir = Path(__file__).parent / "templates" / "discovery"
    
    # Only static files - NO config files
    files_to_copy = [
        "index.html",
        "discovery.js",
        "script.js",
        "discoveryProtocol.js",
        "content-aistudio.js",
        "onboarding.js",
        "styles.css"        
    ]
    
    copied = 0
    for file_name in files_to_copy:
        source = template_dir / file_name
        if source.exists():
            shutil.copy2(source, discovery_dir / file_name)
            copied += 1
            logger.debug(f"    ✓ {file_name}")
        else:
            logger.warning(f"    ⚠️ Template no encontrado: {source}")
    
    logger.debug(f"  ✓ {copied}/{len(files_to_copy)} assets copiados")


# =============================================================================
# DEPRECATED FUNCTIONS - Removed in v3.0
# =============================================================================
# The following functions have been removed and delegated to Sentinel (Go):
#
# - _generate_synapse_config()  → Now in ignition_identity.go::prepareSessionFiles()
# - _generate_launch_id()       → Now in ignition_identity.go::generateLogicalLaunchID()
# - update_discovery_config()   → Config updates via Sentinel's override system
#
# Rationale: Eliminates Python/Go duplication, ensures single source of truth
# for session identity, and simplifies the launch contract.
# =============================================================================