"""
Landing Page Generator - Profile dashboard interface.
Creates ONLY static HTML/CSS/JS assets.

IMPORTANT: Configuration files (landing.synapse.config.js) are now generated 
by Sentinel (Go) during the launch sequence. This module ONLY handles static 
asset deployment.

CHANGELOG v3.0:
- Removed _generate_data_loader() - data injection via Sentinel config
- Removed _copy_synapse_config() - config generated by Sentinel
- Removed _generate_manifest() - metadata managed by Sentinel
- Removed update_landing_data() - data updates via Sentinel override system
- Simplified to pure static asset manager
"""

import shutil
from pathlib import Path
from typing import Dict, Any
from brain.shared.logger import get_logger

logger = get_logger(__name__)


def generate_profile_landing(target_ext_dir: Path, profile_data: Dict[str, Any]) -> None:
    """
    Generates ONLY static landing page assets inside the extension directory.
    
    Configuration files (*.synapse.config.js) and data injection are handled by 
    Sentinel during the launch sequence with proper launch_id and session identity.
    
    Args:
        target_ext_dir: Path to profiles/[UUID]/extension/
        profile_data: Dict with profile metadata (for logging purposes only)
    """
    logger.info(f"🔧 Desplegando assets estáticos de landing para: {profile_data.get('alias')}")
    
    landing_dir = target_ext_dir / "landing"
    landing_dir.mkdir(parents=True, exist_ok=True)
    
    # Deploy static files only
    _copy_static_assets(landing_dir)
    
    logger.info(f"  ✅ Assets estáticos desplegados en: {landing_dir}")
    logger.info(f"  ℹ️  Los archivos de configuración y datos serán generados por Sentinel durante el launch")


def _copy_static_assets(landing_dir: Path) -> None:
    """
    Copies static HTML, CSS, and JS from templates WITHOUT modifications.
    Does NOT include configuration files or data loaders - those are Sentinel's responsibility.
    """
    logger.debug("  📋 Copiando assets estáticos...")
    
    template_dir = Path(__file__).parent / "templates" / "landing"
    
    # Only static files - NO config files, NO data loaders
    files_to_copy = [
        "data-loader.js",
        "index.html",
        "landing.js",
        "landing.synapse.config.js",
        "landingProtocol.js",
        "script.js",
        "styles.css"
    ]
    
    copied = 0
    for file_name in files_to_copy:
        source = template_dir / file_name
        if source.exists():
            shutil.copy2(source, landing_dir / file_name)
            copied += 1
            logger.debug(f"    ✓ {file_name}")
        else:
            logger.warning(f"    ⚠️ Template no encontrado: {source}")
    
    logger.debug(f"  ✓ {copied}/{len(files_to_copy)} assets copiados")


# =============================================================================
# DEPRECATED FUNCTIONS - Removed in v3.0
# =============================================================================
# The following functions have been removed and delegated to Sentinel (Go):
#
# - _copy_synapse_config()    → Config now in ignition_identity.go::prepareSessionFiles()
# - _generate_data_loader()   → Data injection via landing.synapse.config.js (Go)
# - _generate_manifest()      → Metadata managed by Sentinel
# - _format_linked_accounts() → Data formatting in Go
# - _generate_html()          → Replaced by simple copy in _copy_static_assets()
# - update_landing_data()     → Data updates via Sentinel's override system
#
# Rationale: Eliminates Python/Go duplication, ensures single source of truth
# for session identity and profile data, and simplifies the launch contract.
# =============================================================================